name: in_out_ware_app
description: "InOutWareApp"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  componentes_lr:
    path: C:\Repository\Flutter_X_Components_Flutter

  sale_module:
    path: C:\Repository\sale_module

  stock_module:
    path: C:\Repository\stock_module

  transfer_module:
    path: C:\Repository\transfer_module

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  package_info_plus: ^8.1.2
  responsive_framework: ^0.2.0
  shared_preferences: ^2.3.3
  window_size: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: 0.20.2

flutter:
  uses-material-design: true